

  BASKET_TOTAL = 65

  BASKET_DISCOUNT_THRESHOLD = 60
  DISCOUNT_PERCENTAGE = 10
  PRODUCT_CODE = "001"
  PRODUCT_NAME = "Lavender heart"
  PRODUCT_PRICE = 9.25
  DISCOUNT_PRICE = 8.50
  DISCOUNT_THESHOLD = 2
