

  BASKET_TOTAL = 6500

  BASKET_DISCOUNT_THRESHOLD = 6000
  DISCOUNT_PERCENTAGE = 10
  PRODUCT_CODE = "001"
  PRODUCT_NAME = "Lavender heart"
  PRODUCT_PRICE = 925
  DISCOUNT_PRICE = 850
  DISCOUNT_THESHOLD = 2
